runtime: nodejs8
env: standard
service: vue-cli-simple-with-prettier

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
