# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

deploy-steps: &deploy-steps
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run: curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - run: apt-get install -y nodejs
    - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - run: gcloud config set project ruben-oostinga-speeltuin
    - run:
        command: ./scripts/deploy.sh "${CIRCLE_JOB}" "${CIRCLE_BUILD_NUM}"
        no_output_timeout: 15m
    - run: ./scripts/clean-versions.sh "${CIRCLE_JOB}"

version: 2
general:
  branches:
    only:
      - master
jobs:
  angular-cli:
    <<: *deploy-steps
  create-react-app:
    <<: *deploy-steps
  nextjs:
    <<: *deploy-steps
  polymer-2-application:
    <<: *deploy-steps
  vue-cli-default:
    <<: *deploy-steps
  vue-cli-nuxt:
    <<: *deploy-steps
  vue-cli-simple-with-prettier:
    <<: *deploy-steps
  gatsby:
    <<: *deploy-steps


workflows:
  version: 2
  deploy_all:
    jobs:
      - angular-cli
      - create-react-app
      - nextjs
      - polymer-2-application
      - vue-cli-default
      - vue-cli-nuxt
      - vue-cli-simple-with-prettier
      - gatsby

