# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
build-steps: &build-steps
  docker:
    - image: circleci/node
  steps:
    - checkout
    - run: npm install
    - run: npm build

deploy-steps: &deploy-steps
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - run: gcloud config set project ruben-oostinga-speeltuin
    - run:
        command: ./scripts/deploy.sh "${CIRCLE_JOB}" "${CIRCLE_BUILD_NUM}"
        no_output_timeout: 15m
    - run: ./scripts/clean-versions.sh "${CIRCLE_JOB}"

version: 2
jobs:
  build-angular-cli:
    <<: *build-steps
  build-create-react-app:
    <<: *build-steps
  build-nextjs:
    <<: *build-steps
  build-polymer-2-application:
    <<: *build-steps
  build-vue-cli-default:
    <<: *build-steps
  build-vue-cli-nuxt:
    <<: *build-steps
  build-vue-cli-simple-with-prettier:
    <<: *build-steps
  angular-cli:
    <<: *deploy-steps
  create-react-app:
    <<: *deploy-steps
  nextjs:
    <<: *deploy-steps
  polymer-2-application:
    <<: *deploy-steps
  vue-cli-default:
    <<: *deploy-steps
  vue-cli-nuxt:
    <<: *deploy-steps
  vue-cli-simple-with-prettier:
    <<: *deploy-steps

workflows:
  version: 2
  deploy_all:
    jobs:
      - build-angular-cli
      - build-create-react-app
      - build-nextjs
      - build-polymer-2-application
      - build-vue-cli-default
      - build-vue-cli-nuxt
      - build-vue-cli-simple-with-prettier
      - angular-cli:
          requires:
          - build-angular-cli
      - create-react-app:
          requires:
          - build-create-react-app
      - nextjs:
          requires:
          - build-nextjs
      - polymer-2-application:
          requires:
          - build-polymer-2-application
      - vue-cli-default:
          requires:
          - build-vue-cli-default
      - vue-cli-nuxt:
          requires:
          - build-vue-cli-nuxt
      - vue-cli-simple-with-prettier:
          requires:
          - build-vue-cli-simple-with-prettier

