# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

deploy-steps: &deploy-steps
  docker:
    - image: google/cloud-sdk
  steps:
    - checkout
    - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run: cat ${HOME}/gcloud-service-key.json
    - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - run: gcloud config set project ruben-oostinga-speeltuin
    - run: cd packages/${CIRCLE_JOB} && gcloud -q app deploy

version: 2
jobs:
  angular-cli:
    <<: *deploy-steps
  create-nuxt-app-spa:
    <<: *deploy-steps
  create-nuxt-app-universal:
    <<: *deploy-steps
  create-react-app:
    <<: *deploy-steps
  nextjs:
    <<: *deploy-steps
  polymer-2-application:
    <<: *deploy-steps
  vue-cli-default:
    <<: *deploy-steps
  vue-cli-nuxt:
    <<: *deploy-steps
  vue-cli-simple-with-prettier:
    <<: *deploy-steps

workflows:
  version: 2
  deploy_all:
    jobs:
      - angular-cli
      - create-nuxt-app-spa
      - create-nuxt-app-universal
      - create-react-app
      - nextjs
      - polymer-2-application
      - vue-cli-default
      - vue-cli-nuxt
      - vue-cli-simple-with-prettier

